### ISSUE TITLE
Label texts of Export Confirmation buttons (Cancel / somethin else) are not shown

### ISSUE THREAD

**Issue by jnachtigall** [boazpoolman/strapi-plugin-config-sync#108]
### Steps to reproduce the behavior

1. Go to Settings -> Config Sync ->Interface
2. Click on `Export`
3. Confirmation window opens
4. Correct translated labels are missing. Text is cut.

### Expected behavior

Label buttons' text should be correct and understandable. For the 1st button left one can somehow guess that it should mean "Cancel", for the 2nd button it is hard to guess.

### Screenshots

![image](https://github.com/boazpoolman/strapi-plugin-config-sync/assets/3307404/8b101140-ff07-433e-968b-07305db76ac5)

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version:     v18.17.1
- NPM version: 9.6.7
- Strapi version: v4.11.3
- Plugin version: 1.2.0
- Database: Postgres
- Operating system: Linux

### Additional context

I also already had this issue in plugin version 1.1. I think it is present for some month already. I am based in Germany, but my browser (firefox) language is actually English. Not sure, but looks like the plugin is not able to load the translation locales and instead prints out some kind variable.label.name notation. Which is then even cropped due to inflexible width.

**Comment by boazpoolman** [comment]
Hi @jnachtigall 

I see in your screenshot what the problem is, though I'm unable to replicate this issue on my machine.
The code for these translations haven't been touched in a while anyways.

The only way I could think of how this could go wrong is if the plugin is installed with an incorrect identifier.
In the screenshot all those weird texts all start with `config-sync`. That's because the plugin expects the plugin to be installed using `config-sync` as the plugin identifier. If you were to install the plugin using any other key this issue could be replicated.

Did you maby make a typo in the `config/plugins.js` file or anywhere else?

**Comment by boazpoolman** [comment]
Hi @jnachtigall 
Just checking in here. Did you manage to take a look at my comment here above?

**Comment by jnachtigall** [comment]
> The only way I could think of how this could go wrong is if the plugin is installed with an incorrect identifier.
> In the screenshot all those weird texts all start with config-sync. That's because the plugin expects the plugin to be installed using config-sync as the plugin identifier. If you were to install the plugin using any other key this issue could be replicated.

Sorry for the late reply, I was on vacation. Yeah, I guess that's why. I was using a fork which had a different package name (not config-sync but with a local package scope prefixed). 

Thanks for explaining. I could fix it now.
