### ISSUE TITLE
Authenticated and Public settings always appears at changes on settings

### ISSUE THREAD

**Issue by SalahAdDin** [boazpoolman/strapi-plugin-config-sync#12]
Every time we make changes on setting files and we go to see them on the _Config Sync_ panel we see both **Authenticated** and **Public**:
![image](https://user-images.githubusercontent.com/5034215/119225066-4ebcdf80-bb0a-11eb-8cef-3aa449548a11.png)
![image](https://user-images.githubusercontent.com/5034215/119225145-bc690b80-bb0a-11eb-867a-fa39f456bb6c.png)
As you can see, we imported the changes at first time (image 1); later, we made changes and we go to import them again (image 2); and we see them again.

Why? Is it a normal behaviour? It confuses us too much.

**Comment by boazpoolman** [comment]
Hi @SalahAdDin,
Thank you for yet another issue submission!
This is very helpfull to make the plugin better :)

The public & authenticated roles are the default roles in Strapi.
As you can see on the right side these are only in the DB. So no config files are exported for these roles.
If you import them, they will be deleted. But upon refresh, Strapi will automatically create them again, because these are the default roles. This is why they keep coming back.

You will need to export these before they will be fully integrated in the syncing process.
Does that make sense?

What I only do not understand is why they are not exported allready. That should have happend on the initial export.

Please let me know if this makes sense to you.
I think a big part of making this plugin better is to make it understandable and transparent for everybody.
So maby we can figure out a way to do that! :)

**Comment by SalahAdDin** [comment]
It is clear for me now, it seems i didn't read the state carefully but it has sense for me; after exporting it, i don't see them again.

Maybe you could improve the documentation if you think it worths.

Thanks.

**Comment by boazpoolman** [comment]
I will add some documentation for this. 
This will probably be a small text right by the list item in de differences tool for the public & authenticated roles.
Text will be something like 'The default roles in Strapi will not be deleted on import.'

**Comment by SalahAdDin** [comment]
Well, it confuses me a bit: we exported the permission for the content types we use in our instance, we want to import them later.

My mistake was i misunderstood what "Only database" label means.

**Comment by boazpoolman** [comment]
I added some logging to the CLI to show a warning when you delete a default role.
<img width="634" alt="Screenshot 2021-12-29 at 02 15 12" src="https://user-images.githubusercontent.com/9551934/147618777-5af30146-5317-4f46-ae7d-83c953523217.png">
Was released with `v1.0.0-beta.1`
