### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by danielehrhardt** [boazpoolman/strapi-plugin-config-sync#14]
`error: unable to create file extensions/config-sync/files/core-store.plugin_content_manager_configuration_content_types::plugins::users-permissions.user.json: Invalid argument`

you could remove the : from the File Name. 
This does not work on NTFS. So it does not work on Windows.

**Comment by alexzrp** [comment]
https://github.com/boazpoolman/strapi-plugin-config-sync/pull/16

**Comment by boazpoolman** [comment]
This issue was fixed by changing all the `:` characters to `#` in the filenames.
Thanks @alexzrp for the work.

Released in [v1.0.0-alpha.1](https://github.com/boazpoolman/strapi-plugin-config-sync/releases/tag/1.0.0-alpha.1) for the Strapi v4 version of  of `strapi-plugin-config-sync`.

If you're still experiencing issues with Windows beyond version `1.0.0-alpha.1` feel free to re-open this issue.
