### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'S') at x.default.theme

### ISSUE THREAD

**Issue by diacu** [boazpoolman/strapi-plugin-config-sync#83]
### Describe the bug

When navigating to Settings -> Config Sync (/admin/settings/config-sync) I get a blank page. 

### Steps to reproduce the behavior

1. Go to 'Settings'
2. Click on 'Interface' under 'Config Sync'
3. See error

### Expected behavior

I should see the Diff with config files and Import / Export buttons.

### Screenshots

https://wsnd.io/nfDKOrdu/Screenshot%202023-01-21%20at%2011.14.56.png

### System

- Node.js version: v16.17.0
- Yarn version: v1.22.19
- Strapi version: 4.5.6
- Plugin version: 1.1.0
- Database: MySQL
- Operating system: Ubuntu 18.04

**Comment by boazpoolman** [comment]
Hey @diacu,

Thank you for reporting the issue.
I’ve ran the CI on your PR and as I expected it failed on linting because the updated button import is unresolved.

See the failed CI output here https://github.com/boazpoolman/strapi-plugin-config-sync/actions/runs/3974200216/jobs/6813678040

I’ll try to reproduce the issue but I can’t imagine updating the button import fixes the issue.

**Comment by boazpoolman** [comment]
Hey @diacu,

Thank you for reporting the issue. I'll try to reproduce it as soon as I have the time.
